#rest api example new
###
GET http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/products/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json
    
{
    "name": "Casco Inteligente",
    "price": 300,
    "category": "Gps",
    "image": "https://fotos02.formulamoto.es/2017/06/13/646x260/cascomotointeligente.jpeg"    
}

###
PUT http://localhost:3000/api/products/5fd16a2543fc6749d86c6009 HTTP/1.1
Content-Type: application/json

{
    "name": "Alarma de Alejamiento ",
    "price": 180,
    "category": "Alejamiento",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_4NXwm9lqOomBaVQpxPPbTZU4kvpq4c887w&usqp=CAU"
}

###
DELETE http://localhost:3000/api/products/5fd16a2543fc6749d86c6009 HTTP/1.1
Content-Type: application/json
